import Footer from "@/components/footer";
import Header from "@/components/header";
import WhatsAppFloat from "@/components/WhatsAppFloat";
import type { Metadata } from "next";
import { DynaPuff, Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const dynaPuff = DynaPuff({
  variable: "--font-dynapuff",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} ${dynaPuff.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <main>{children}</main>
        {/* Floating WhatsApp button — always visible, bottom-right corner */}
        <WhatsAppFloat />
        <Footer />
      </body>
    </html>
  );
}
